apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    pid /tmp/nginx.pid;
    error_log /tmp/error.log;
    events {
      worker_connections 1024;
    }
    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path /tmp/proxy_temp;
      fastcgi_temp_path /tmp/fastcgi_temp;
      uwsgi_temp_path /tmp/uwsgi_temp;
      scgi_temp_path /tmp/scgi_temp;
      
      server {
        listen 8080;
        access_log /tmp/access.log;
        location / {
          root /usr/share/nginx/html;
          autoindex on;
        }
      }
    }
