apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: hello-chris-ai-test
  namespace: hello-chris-ai
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: "SkipDryRunOnMissingResource=true"
spec:
  serviceAccountName: pipeline
  pipelineRef:
    name: hello-chris-ai-pipeline
  params:
  - name: namespace
    value: "hello-chris-ai"
  - name: deployment-name
    value: "hello-chris-ai"
  - name: git-url
    value: "https://github.com/cnuland/k8s-hello-chris-ai-regression.git"
  - name: git-revision
    value: "main"
  - name: IMAGE
    value: "quay.io/cnuland/ppo-notebook"
  - name: TLSVERIFY
    value: "false"
  - name: NO_PROXY
    value: "true"
  - name: working-dir
    value: "notebook"
  workspaces:
  - name: shared-workspace
    persistentvolumeclaim:
      claimName: tekton-pvc
